title: SubOrbital Records
description: A fictional music label inspired by Star Citizen.
url: ""            # laisse vide pour GitHub Pages
baseurl: ""        # vide si tu publies sur un domaine dédié ; sinon "/suborbital"
lore_year_offset: 930

markdown: kramdown

collections:
  artists:
    output: true
    permalink: /artists/:name/
  tracks:
    output: false
  releases:
    output: true
    permalink: /releases/:name/
  upcoming:
    output: false
  press:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: artists
    values:
      layout: artist
  - scope:
      path: ""
      type: releases
    values:
      layout: release

exclude:
  - README.md
  - node_modules
  - vendor
